queue_rules:
  - name: default
    conditions:
      - check-success=jenkins/blocks-sdk-github

pull_request_rules:
  - name: Automatic merge ⬇ on approval ✔
    conditions:
      - and:
        - base=main
        - "#approved-reviews-by>=1"
        - label=mergeme
        - check-success=jenkins/blocks-sdk-github
    actions:
      queue:
        commit_message: title+body
        method: squash
        name: default
        rebase_fallback: none
      delete_head_branch:
        force: true


  - name: Emergency merge ⬇
    conditions:
      - and:
        - base=main
        - label=emergency-mergeme
    actions:
      merge:
        commit_message: title+body
        method: squash
        rebase_fallback: none
