toc:
    - name: '@airtable/blocks'
      children:
          - BlockSdk
          - RunInfo
          - GlobalConfig
    - name: '@airtable/blocks/models'
      children:
          - Base
          - Table
          - View
          - Field
          - QueryResult
          - Record
    - name: '@airtable/blocks/ui'
      children:
          - name: Button
            children:
                - Button
                - ButtonProps
          - Icon
