import {ObjectMap} from '../../src/private_utils';

export enum FieldType {
    SINGLE_LINE_TEXT = 'singleLineText',
    EMAIL = 'email',
    URL = 'url',
    MULTILINE_TEXT = 'multilineText',
    NUMBER = 'number',
    PERCENT = 'percent',
    CURRENCY = 'currency',
    SINGLE_SELECT = 'singleSelect',
    MULTIPLE_SELECTS = 'multipleSelects',
    SINGLE_COLLABORATOR = 'singleCollaborator',
    MULTIPLE_COLLABORATORS = 'multipleCollaborators',
    MULTIPLE_RECORD_LINKS = 'multipleRecordLinks',
    DATE = 'date',
    DATE_TIME = 'dateTime',
    PHONE_NUMBER = 'phoneNumber',
    MULTIPLE_ATTACHMENTS = 'multipleAttachments',
    CHECKBOX = 'checkbox',
    FORMULA = 'formula',
    CREATED_TIME = 'createdTime',
    ROLLUP = 'rollup',
    COUNT = 'count',
    LOOKUP = 'lookup',
    AUTO_NUMBER = 'autoNumber',
    BARCODE = 'barcode',
    RATING = 'rating',
    RICH_TEXT = 'richText',
    DURATION = 'duration',
    LAST_MODIFIED_TIME = 'lastModifiedTime',
}

export const ReadableFieldTypes: ObjectMap<FieldType, string> = {
    [FieldType.SINGLE_LINE_TEXT]: 'Single line text',
    [FieldType.EMAIL]: 'Email',
    [FieldType.URL]: 'URL',
    [FieldType.MULTILINE_TEXT]: 'Long text',
    [FieldType.NUMBER]: 'Number',
    [FieldType.PERCENT]: 'Percent',
    [FieldType.CURRENCY]: 'Currency',
    [FieldType.SINGLE_SELECT]: 'Single select',
    [FieldType.MULTIPLE_SELECTS]: 'Multiple select',
    [FieldType.SINGLE_COLLABORATOR]: 'Collaborator (single)',
    [FieldType.MULTIPLE_COLLABORATORS]: 'Collaborators (multiple)',
    [FieldType.MULTIPLE_RECORD_LINKS]: 'Linked records',
    [FieldType.DATE]: 'Date',
    [FieldType.DATE_TIME]: 'Date with time',
    [FieldType.PHONE_NUMBER]: 'Phone number',
    [FieldType.MULTIPLE_ATTACHMENTS]: 'Attachment',
    [FieldType.CHECKBOX]: 'Checkbox',
    [FieldType.FORMULA]: 'Formula',
    [FieldType.CREATED_TIME]: 'Created time',
    [FieldType.ROLLUP]: 'Rollup',
    [FieldType.COUNT]: 'Count',
    [FieldType.LOOKUP]: 'Lookup',
    [FieldType.AUTO_NUMBER]: 'Autonumber',
    [FieldType.BARCODE]: 'Barcode',
    [FieldType.RATING]: 'Rating',
    [FieldType.RICH_TEXT]: 'Rich text',
    [FieldType.DURATION]: 'Duration',
    [FieldType.LAST_MODIFIED_TIME]: 'Last modified time',
};
