// flow-typed signature: 2bdb98d83d459a2deb26717e62c75392
// flow-typed version: <<STUB>>/es6-promisify_v^5.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promisify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promisify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-promisify/dist/promise' {
  declare module.exports: any;
}

declare module 'es6-promisify/dist/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-promisify/dist/promise.js' {
  declare module.exports: $Exports<'es6-promisify/dist/promise'>;
}
declare module 'es6-promisify/dist/promisify.js' {
  declare module.exports: $Exports<'es6-promisify/dist/promisify'>;
}
