// flow-typed signature: 136177eaba8d684ec758ccde1999aef7
// flow-typed version: <<STUB>>/npm-package-arg_v6.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-package-arg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-package-arg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-package-arg/npa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-package-arg/npa.js' {
  declare module.exports: $Exports<'npm-package-arg/npa'>;
}
