// flow-typed signature: f06916f91bdf717d6ad0af9e8a0c8cfb
// flow-typed version: <<STUB>>/terser_v^3.17.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terser/dist/bundle' {
  declare module.exports: any;
}

declare module 'terser/dist/bundle.min' {
  declare module.exports: any;
}

declare module 'terser/tools/colorless-console' {
  declare module.exports: any;
}

declare module 'terser/tools/domprops' {
  declare module.exports: any;
}

declare module 'terser/tools/exit' {
  declare module.exports: any;
}

declare module 'terser/tools/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terser/dist/bundle.js' {
  declare module.exports: $Exports<'terser/dist/bundle'>;
}
declare module 'terser/dist/bundle.min.js' {
  declare module.exports: $Exports<'terser/dist/bundle.min'>;
}
declare module 'terser/tools/colorless-console.js' {
  declare module.exports: $Exports<'terser/tools/colorless-console'>;
}
declare module 'terser/tools/domprops.js' {
  declare module.exports: $Exports<'terser/tools/domprops'>;
}
declare module 'terser/tools/exit.js' {
  declare module.exports: $Exports<'terser/tools/exit'>;
}
declare module 'terser/tools/node.js' {
  declare module.exports: $Exports<'terser/tools/node'>;
}
