// flow-typed signature: f79c96a857a414ed5cec44b13f2da0c7
// flow-typed version: <<STUB>>/envify_v^4.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'envify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'envify' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'envify/custom' {
    declare module.exports: any;
}

// Filename aliases
declare module 'envify/custom.js' {
    declare module.exports: $Exports<'envify/custom'>;
}
declare module 'envify/index' {
    declare module.exports: $Exports<'envify'>;
}
declare module 'envify/index.js' {
    declare module.exports: $Exports<'envify'>;
}
