// flow-typed signature: 73549b910350b3ce8590e7789a5ccc48
// flow-typed version: <<STUB>>/eslint-plugin-class-property_v^1.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-class-property'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-class-property' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-class-property/lib/rules/class-property-semicolon' {
    declare module.exports: any;
}

declare module 'eslint-plugin-class-property/test/lib/rules/class-property-semicolon' {
    declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-class-property/index' {
    declare module.exports: $Exports<'eslint-plugin-class-property'>;
}
declare module 'eslint-plugin-class-property/index.js' {
    declare module.exports: $Exports<'eslint-plugin-class-property'>;
}
declare module 'eslint-plugin-class-property/lib/rules/class-property-semicolon.js' {
    declare module.exports: $Exports<
        'eslint-plugin-class-property/lib/rules/class-property-semicolon',
    >;
}
declare module 'eslint-plugin-class-property/test/lib/rules/class-property-semicolon.js' {
    declare module.exports: $Exports<
        'eslint-plugin-class-property/test/lib/rules/class-property-semicolon',
    >;
}
