// flow-typed signature: b9a41ef661dfb6fa790d6274269f191c
// flow-typed version: <<STUB>>/prompt_v^1.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prompt' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prompt/examples/add-properties' {
    declare module.exports: any;
}

declare module 'prompt/examples/color' {
    declare module.exports: any;
}

declare module 'prompt/examples/dynamic-ask-prompt' {
    declare module.exports: any;
}

declare module 'prompt/examples/existing-properties' {
    declare module.exports: any;
}

declare module 'prompt/examples/history' {
    declare module.exports: any;
}

declare module 'prompt/examples/nested-properties-prompt' {
    declare module.exports: any;
}

declare module 'prompt/examples/old-schema' {
    declare module.exports: any;
}

declare module 'prompt/examples/override-validation' {
    declare module.exports: any;
}

declare module 'prompt/examples/password' {
    declare module.exports: any;
}

declare module 'prompt/examples/prompt-override' {
    declare module.exports: any;
}

declare module 'prompt/examples/property-prompt' {
    declare module.exports: any;
}

declare module 'prompt/examples/simple-prompt' {
    declare module.exports: any;
}

declare module 'prompt/examples/types' {
    declare module.exports: any;
}

declare module 'prompt/examples/yes-or-no-prompt' {
    declare module.exports: any;
}

declare module 'prompt/lib/prompt' {
    declare module.exports: any;
}

declare module 'prompt/test/helpers' {
    declare module.exports: any;
}

declare module 'prompt/test/interactive-prompt-test' {
    declare module.exports: any;
}

declare module 'prompt/test/macros' {
    declare module.exports: any;
}

declare module 'prompt/test/prompt-test' {
    declare module.exports: any;
}

// Filename aliases
declare module 'prompt/examples/add-properties.js' {
    declare module.exports: $Exports<'prompt/examples/add-properties'>;
}
declare module 'prompt/examples/color.js' {
    declare module.exports: $Exports<'prompt/examples/color'>;
}
declare module 'prompt/examples/dynamic-ask-prompt.js' {
    declare module.exports: $Exports<'prompt/examples/dynamic-ask-prompt'>;
}
declare module 'prompt/examples/existing-properties.js' {
    declare module.exports: $Exports<'prompt/examples/existing-properties'>;
}
declare module 'prompt/examples/history.js' {
    declare module.exports: $Exports<'prompt/examples/history'>;
}
declare module 'prompt/examples/nested-properties-prompt.js' {
    declare module.exports: $Exports<'prompt/examples/nested-properties-prompt'>;
}
declare module 'prompt/examples/old-schema.js' {
    declare module.exports: $Exports<'prompt/examples/old-schema'>;
}
declare module 'prompt/examples/override-validation.js' {
    declare module.exports: $Exports<'prompt/examples/override-validation'>;
}
declare module 'prompt/examples/password.js' {
    declare module.exports: $Exports<'prompt/examples/password'>;
}
declare module 'prompt/examples/prompt-override.js' {
    declare module.exports: $Exports<'prompt/examples/prompt-override'>;
}
declare module 'prompt/examples/property-prompt.js' {
    declare module.exports: $Exports<'prompt/examples/property-prompt'>;
}
declare module 'prompt/examples/simple-prompt.js' {
    declare module.exports: $Exports<'prompt/examples/simple-prompt'>;
}
declare module 'prompt/examples/types.js' {
    declare module.exports: $Exports<'prompt/examples/types'>;
}
declare module 'prompt/examples/yes-or-no-prompt.js' {
    declare module.exports: $Exports<'prompt/examples/yes-or-no-prompt'>;
}
declare module 'prompt/lib/prompt.js' {
    declare module.exports: $Exports<'prompt/lib/prompt'>;
}
declare module 'prompt/test/helpers.js' {
    declare module.exports: $Exports<'prompt/test/helpers'>;
}
declare module 'prompt/test/interactive-prompt-test.js' {
    declare module.exports: $Exports<'prompt/test/interactive-prompt-test'>;
}
declare module 'prompt/test/macros.js' {
    declare module.exports: $Exports<'prompt/test/macros'>;
}
declare module 'prompt/test/prompt-test.js' {
    declare module.exports: $Exports<'prompt/test/prompt-test'>;
}
