// flow-typed signature: 858b00f11870aa954151b390f81a79ab
// flow-typed version: <<STUB>>/@deboxsoft/cpx_v1.5.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@deboxsoft/cpx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@deboxsoft/cpx' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@deboxsoft/cpx/bin/help' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/bin' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/bin/main' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/bin/version' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/copy-sync' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/copy' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/apply-action-sync' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/apply-action' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/copy-file-sync' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/copy-file' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/normalize-options' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/normalize-path' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/remove-file-sync' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/remove-file' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/utils/watcher' {
    declare module.exports: any;
}

declare module '@deboxsoft/cpx/lib/watch' {
    declare module.exports: any;
}

// Filename aliases
declare module '@deboxsoft/cpx/bin/help.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/bin/help'>;
}
declare module '@deboxsoft/cpx/bin/index' {
    declare module.exports: $Exports<'@deboxsoft/cpx/bin'>;
}
declare module '@deboxsoft/cpx/bin/index.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/bin'>;
}
declare module '@deboxsoft/cpx/bin/main.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/bin/main'>;
}
declare module '@deboxsoft/cpx/bin/version.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/bin/version'>;
}
declare module '@deboxsoft/cpx/lib/copy-sync.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/copy-sync'>;
}
declare module '@deboxsoft/cpx/lib/copy.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/copy'>;
}
declare module '@deboxsoft/cpx/lib/index' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib'>;
}
declare module '@deboxsoft/cpx/lib/index.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib'>;
}
declare module '@deboxsoft/cpx/lib/utils/apply-action-sync.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/apply-action-sync'>;
}
declare module '@deboxsoft/cpx/lib/utils/apply-action.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/apply-action'>;
}
declare module '@deboxsoft/cpx/lib/utils/copy-file-sync.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/copy-file-sync'>;
}
declare module '@deboxsoft/cpx/lib/utils/copy-file.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/copy-file'>;
}
declare module '@deboxsoft/cpx/lib/utils/normalize-options.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/normalize-options'>;
}
declare module '@deboxsoft/cpx/lib/utils/normalize-path.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/normalize-path'>;
}
declare module '@deboxsoft/cpx/lib/utils/remove-file-sync.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/remove-file-sync'>;
}
declare module '@deboxsoft/cpx/lib/utils/remove-file.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/remove-file'>;
}
declare module '@deboxsoft/cpx/lib/utils/watcher.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/utils/watcher'>;
}
declare module '@deboxsoft/cpx/lib/watch.js' {
    declare module.exports: $Exports<'@deboxsoft/cpx/lib/watch'>;
}
