commitSha = '';
branch = '';
final personOrSystemThatTriggeredBuild = params.getOrDefault('AUTHOR_NAME', env.AUTHOR_NAME ?: 'jenkins');
final branchNameForDisplayOnly = params.getOrDefault('BRANCH_NAME_FOR_DISPLAY_IN_SUMMARY_AND_IS_NOT_ACTUALLY_WHAT_IS_BUILT', env.BRANCH_NAME_FOR_DISPLAY_IN_SUMMARY_AND_IS_NOT_ACTUALLY_WHAT_IS_BUILT ?: 'Branch name is unknown');

stashedDirectories = [];

pipeline {
    options {
        timestamps();
        timeout(time: 20, unit: 'MINUTES');
    }

    // Let each individual stage determine the host (and possibly container) where it is run
    agent none;

    stages {
        stage('Report progress Phabricator') {
            steps {
                script {
                    // Run on the master node, to report back immediately to Phabricator without possibly waiting for a new EC2 worker to be provisioned.
                    node('master') {
                        // Tells a lambda to post to a Phabricator diff, to set a link to this Jenkins job.
                        postBackToPhabricatorIfNecessary("pending");

                        // This build description is optimized for the Jenkins job that is triggered by Phacility diffs.
                        def revisionId = params.get('REVISION_ID')
                        def revisionUrl = "https://airtable.phacility.com/D${revisionId}?id=${params.get('DIFF_ID')}";
                        def revisionLink = params.getOrDefault('REVISION_ID', false) ? "<a href=\"${revisionUrl}\">D${revisionId}</a><br/>" : "";
                        def gitRefOrDefault = params.getOrDefault('GIT_REF', scm.branches[0].name);
                        def gitRefOrDefaultLink = "<a href=\"https://github.com/Hyperbase/hyperbase/tree/${gitRefOrDefault}\">${gitRefOrDefault}</a>";
                        def displayBranchLink = "The branch is <a href=\"https://github.com/hyperbase/hyperbase/tree/${branchNameForDisplayOnly}\">${branchNameForDisplayOnly}</a>";
                        def feedbackLink = "<a href=\"https://airtable.com/shr9LjyNcD6rUUFAN\">Submit feedback to the Production Engineering team here</a>";
                        def playbookLink = "How should you interpret this page? <a href=\"https://docs.google.com/document/d/1xzPmMYLrI0MtNiqSewZwu90X_paM_9aod9DcoV6Tihs/edit#heading=h.h83xxogp9l2b\">Read this playbook</a>";
                        // NOTE: revisionLink and gitRefOrDefaultLink intentionally have the URL as the first part of the line, so that the job summaries that Jenkins
                        // shows on the the left side of the homepage will include the URL (rather than generic text).
                        currentBuild.description = "${revisionLink}${gitRefOrDefaultLink} for ${personOrSystemThatTriggeredBuild}<br/>${displayBranchLink}<br/>${playbookLink}<br/>${feedbackLink}<br/>";
                    }
                }
            }
        }
        stage('Blocks-sdk tests') {
            agent {
                docker {
                    image 'node:12.20.1-buster'
                    // The label indicates which EC2 configuration to use, which are configured in https://jenkins.hyperbasedev.com/configureClouds/
                    label 'jenkins-worker-for-blocks-tests'
                }
            }
            steps {
                script {
                    sshagent(['github2']) {
                        sh '''#!/bin/bash
                        set -euo pipefail
                        set -x
                        printenv
                        yarn --version
                        node --version
                        mkdir -p ~/.ssh
                        echo github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== >> ~/.ssh/known_hosts
                        yarn install
                        yarn ci
                        '''
                    }
                }
            }
            post {
                always {
                    script {
                        currentBuild.description += "The build took ${currentBuild.duration/60000} minutes";

                        // Post status before doing any other processing, to get these updates out ASAP.
                        postBackToPhabricatorIfNecessary(getTerminalResultForPhacilityAndSlack());
                        notifySlack();

                        cleanWs();
                    }
                }
            }
        }
    }
}


def getTerminalResultForPhacilityAndSlack() {
    def resultForPhacility = 'failed';
    if (currentBuild.currentResult == 'SUCCESS' || currentBuild.currentResult == 'UNSTABLE') {
        resultForPhacility = 'passed';
    }
    return resultForPhacility;
}

def notifySlack() {
    def resultForPhacilityAndSlack = getTerminalResultForPhacilityAndSlack();
    try {
        def channelsToNotify = [];
        // Send a notification to a channel that Prod Eng (and other interested parties) can monitor.
        channelsToNotify.add('#jenkins-feed');
        // FIXME_CICD use some constants
        if (env.JOB_NAME == 'blocks-sdk-main' && resultForPhacilityAndSlack == 'failed') {
            // When main fails, send it to a channel that all platform engineers are members of.
            channelsToNotify.add('#team-ecosystem-dev-feed');
        }
        channelsToNotify.each {
            // In Slack, the Jenkins app configuration is here: https://h.slack.com/services/B01DK46MT5Y?added=1
            // In Jenkins, the configuration instructions are: https://www.baeldung.com/jenkins-slack-integration and https://plugins.jenkins.io/slack/
            def slackColor = resultForPhacilityAndSlack == 'passed' ? 'good' : 'danger';
            // Guard against commitSha not being set.
            def shaShort = commitSha.length() >= 8 ? commitSha[0..7] : commitSha;
            slackSend(
                channel: "${it}",
                message: "*Tests have ${resultForPhacilityAndSlack} on <https://github.com/Hyperbase/blocks-sdk/tree/${commitSha}|${branch} (${shaShort})> *\n<${env.BUILD_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>",
                color: slackColor,
                tokenCredentialId: 'slack-oauth-token2'
            );
        }
    } catch (Exception e) {
        // This post block should continue processing even if there's a failure in this method.
        // FIXME_CID add stack trace to the output, otherwise it may be hard to determine which line threw it
        print "Suppressed error when posting to Slack: ${e}"
    }
}

// Note: this script block runs on a Jenkins instance that does NOT have a checkout of a branch, so the logic needs to be contained in this Jenkinsfile as opposed to e.g. a script in the branch.
// Note: this Jenkinsfile is called by at least three Jenkins jobs: "hyperbase-ad-hoc", "hyperbase-master", and "hyperbase-phacility"
// Note: why didn't I use the Phabricator-Jenkins plugin (https://github.com/uber/phabricator-jenkins-plugin)? The main reason is that it doesn't support Groovy Pipelines out of the box
//       (i.e. this type of job). I found some plausible set up instructions buried in a github thread: https://github.com/uber/phabricator-jenkins-plugin/issues/198#issuecomment-646132563
//       but my intuition is that there will be other significant challenges to using the plugin. So I'm going to continue using our existing lambdas.
//       Arguably continuing to use lambdas have worse tradeoffs (they're nearly impossible for engineers to inspect; they're very cumbersome to test and deploy)
//       However, we can revisit this decision later, since this component can be swapped out.
// FIXME_CICD: consider loading logic from separate Jenkins files, like in: https://github.com/ksuther/jenkins-jenkinsfile-include/blob/master/Jenkinsfile
def postBackToPhabricatorIfNecessary(status) {
    try {
        // Report the build result to phacility.
        // NOTE: this phid is the Harbormaster build target phid associated with this build run.
        if (params.getOrDefault('PHID', false)) {
            // Tells a lambda to post to a Phabricator diff, to set the status as of this job as "passed" or "failed"
            sh """curl --silent --show-error --retry 4 --max-time 5 -XPOST 'https://airbuild.hyperbasedev.com/airbuildWebhook' \
                    -H 'Content-Type: application/json' \
                    -d '{
                        \"sha\": \"${params.GIT_REF}\",
                        \"automationSystem\": \"jenkins\",
                        \"buildNumber\": ${currentBuild.number},
                        \"failedBuildTailLogUrl\": null,
                        \"diffId\": \"${params.DIFF_ID}\",
                        \"phid\": \"${params.PHID}\",
                        \"jenkinsJobName\": \"${env.JOB_NAME}\",
                        \"jenkinsStatus\": \"${status}\"
                    }' \
                    || echo 'Failed' to report to Phacility
            """;        
        }
    } catch (Exception e) {
        // This post block should continue processing even if there's a failure in this method
        // FIXME_CID add stack trace to the output, otherwise it may be hard to determine which line threw it
        print "Suppressed error when posting to Phacility: ${e}"
    }
}