// @flow
export const BlockToHost = Object.freeze({
    SCRIPT_LOAD_ERROR: ('SCRIPT_LOAD_ERROR': 'SCRIPT_LOAD_ERROR'),
    SCRIPT_RUNTIME_ERROR: ('SCRIPT_RUNTIME_ERROR': 'SCRIPT_RUNTIME_ERROR'),
    CALL_HOST_METHOD: ('CALL_HOST_METHOD': 'CALL_HOST_METHOD'),
    WILL_UNLOAD: ('WILL_UNLOAD': 'WILL_UNLOAD'),
    ON_FOCUS: ('ON_FOCUS': 'ON_FOCUS'),
    ON_BLUR: ('ON_BLUR': 'ON_BLUR'),
    ON_KEY_DOWN: ('ON_KEY_DOWN': 'ON_KEY_DOWN'),
});

export const HostToBlock = Object.freeze({
    SET_MULTIPLE_KV_PATHS: ('SET_MULTIPLE_KV_PATHS': 'SET_MULTIPLE_KV_PATHS'),
    UPDATE_MODELS: ('UPDATE_MODELS': 'UPDATE_MODELS'),
    HOST_METHOD_RESPONSE: ('HOST_METHOD_RESPONSE': 'HOST_METHOD_RESPONSE'),
    FOCUS: ('FOCUS': 'FOCUS'),
    DID_ENTER_FULLSCREEN: ('DID_ENTER_FULLSCREEN': 'DID_ENTER_FULLSCREEN'),
    DID_EXIT_FULLSCREEN: ('DID_EXIT_FULLSCREEN': 'DID_EXIT_FULLSCREEN'),
    DID_CLICK_SETTINGS_BUTTON: ('DID_CLICK_SETTINGS_BUTTON': 'DID_CLICK_SETTINGS_BUTTON'),
});

export const HostMethodNames = Object.freeze({
    REGISTER_FRAME: ('REGISTER_FRAME': 'REGISTER_FRAME'),
    ALL_SCRIPTS_LOADED: ('ALL_SCRIPTS_LOADED': 'ALL_SCRIPTS_LOADED'),
    RELOAD_FRAME: ('RELOAD_FRAME': 'RELOAD_FRAME'),
    FETCH_AND_SUBSCRIBE_TO_TABLE_DATA: ('FETCH_AND_SUBSCRIBE_TO_TABLE_DATA': 'FETCH_AND_SUBSCRIBE_TO_TABLE_DATA'),
    UNSUBSCRIBE_FROM_TABLE_DATA: ('UNSUBSCRIBE_FROM_TABLE_DATA': 'UNSUBSCRIBE_FROM_TABLE_DATA'),
    FETCH_AND_SUBSCRIBE_TO_VIEW_DATA: ('FETCH_AND_SUBSCRIBE_TO_VIEW_DATA': 'FETCH_AND_SUBSCRIBE_TO_VIEW_DATA'),
    UNSUBSCRIBE_FROM_VIEW_DATA: ('UNSUBSCRIBE_FROM_VIEW_DATA': 'UNSUBSCRIBE_FROM_VIEW_DATA'),
    FETCH_DEFAULT_CELL_VALUES_BY_FIELD_ID: ('FETCH_DEFAULT_CELL_VALUES_BY_FIELD_ID': 'FETCH_DEFAULT_CELL_VALUES_BY_FIELD_ID'),
    FETCH_AND_SUBSCRIBE_TO_CELL_VALUES_IN_FIELDS: ('FETCH_AND_SUBSCRIBE_TO_CELL_VALUES_IN_FIELDS': 'FETCH_AND_SUBSCRIBE_TO_CELL_VALUES_IN_FIELDS'),
    UNSUBSCRIBE_FROM_CELL_VALUES_IN_FIELDS: ('UNSUBSCRIBE_FROM_CELL_VALUES_IN_FIELDS': 'UNSUBSCRIBE_FROM_CELL_VALUES_IN_FIELDS'),
    FETCH_AND_SUBSCRIBE_TO_CURSOR_DATA: ('FETCH_AND_SUBSCRIBE_TO_CURSOR_DATA': 'FETCH_AND_SUBSCRIBE_TO_CURSOR_DATA'),
    UNSUBSCRIBE_FROM_CURSOR_DATA: ('UNSUBSCRIBE_FROM_CURSOR_DATA': 'UNSUBSCRIBE_FROM_CURSOR_DATA'),
    EXPAND_RECORD: ('EXPAND_RECORD': 'EXPAND_RECORD'),
    EXPAND_RECORD_LIST: ('EXPAND_RECORD_LIST': 'EXPAND_RECORD_LIST'),
    EXPAND_RECORD_PICKER: ('EXPAND_RECORD_PICKER': 'EXPAND_RECORD_PICKER'),
    SET_MULTIPLE_KV_PATHS: ('SET_MULTIPLE_KV_PATHS': 'SET_MULTIPLE_KV_PATHS'),
    SET_CELL_VALUES: ('SET_CELL_VALUES': 'SET_CELL_VALUES'),
    CREATE_RECORDS: ('CREATE_RECORDS': 'CREATE_RECORDS'),
    DELETE_RECORDS: ('DELETE_RECORDS': 'DELETE_RECORDS'),
    ENTER_FULLSCREEN: ('ENTER_FULLSCREEN': 'ENTER_FULLSCREEN'),
    EXIT_FULLSCREEN: ('EXIT_FULLSCREEN': 'EXIT_FULLSCREEN'),
    SET_FULLSCREEN_MAX_SIZE: ('SET_FULLSCREEN_MAX_SIZE': 'SET_FULLSCREEN_MAX_SIZE'),
    SET_SETTINGS_BUTTON_VISIBILITY: ('SET_SETTINGS_BUTTON_VISIBILITY': 'SET_SETTINGS_BUTTON_VISIBILITY'),
    SET_UNDO_REDO_MODE: ('SET_UNDO_REDO_MODE': 'SET_UNDO_REDO_MODE'),
});

export type BlockToHostMessageType = $Values<typeof BlockToHost>;
export type HostToBlockMessageType = $Values<typeof HostToBlock>;
export type HostMethodName = $Values<typeof HostMethodNames>;
