/** @hidden */ /** */
import {ObjectValues} from '../private_utils';
export const BlockToHost = Object.freeze({
    SCRIPT_LOAD_ERROR: 'SCRIPT_LOAD_ERROR' as const,
    SCRIPT_RUNTIME_ERROR: 'SCRIPT_RUNTIME_ERROR' as const,
    CALL_HOST_METHOD: 'CALL_HOST_METHOD' as const,
    WILL_UNLOAD: 'WILL_UNLOAD' as const,
    ON_FOCUS: 'ON_FOCUS' as const,
    ON_BLUR: 'ON_BLUR' as const,
    ON_KEY_DOWN: 'ON_KEY_DOWN' as const,
});

export const HostToBlock = Object.freeze({
    SET_MULTIPLE_KV_PATHS: 'SET_MULTIPLE_KV_PATHS' as const,
    UPDATE_MODELS: 'UPDATE_MODELS' as const,
    HOST_METHOD_RESPONSE: 'HOST_METHOD_RESPONSE' as const,
    FOCUS: 'FOCUS' as const,
    DID_ENTER_FULLSCREEN: 'DID_ENTER_FULLSCREEN' as const,
    DID_EXIT_FULLSCREEN: 'DID_EXIT_FULLSCREEN' as const,
    DID_CLICK_SETTINGS_BUTTON: 'DID_CLICK_SETTINGS_BUTTON' as const,
});

export const HostMethodNames = Object.freeze({
    REGISTER_FRAME: 'REGISTER_FRAME' as const,
    ALL_SCRIPTS_LOADED: 'ALL_SCRIPTS_LOADED' as const,
    RELOAD_FRAME: 'RELOAD_FRAME' as const,
    FETCH_AND_SUBSCRIBE_TO_TABLE_DATA: 'FETCH_AND_SUBSCRIBE_TO_TABLE_DATA' as const,
    UNSUBSCRIBE_FROM_TABLE_DATA: 'UNSUBSCRIBE_FROM_TABLE_DATA' as const,
    FETCH_AND_SUBSCRIBE_TO_VIEW_DATA: 'FETCH_AND_SUBSCRIBE_TO_VIEW_DATA' as const,
    UNSUBSCRIBE_FROM_VIEW_DATA: 'UNSUBSCRIBE_FROM_VIEW_DATA' as const,
    FETCH_DEFAULT_CELL_VALUES_BY_FIELD_ID: 'FETCH_DEFAULT_CELL_VALUES_BY_FIELD_ID' as const,
    FETCH_AND_SUBSCRIBE_TO_CELL_VALUES_IN_FIELDS: 'FETCH_AND_SUBSCRIBE_TO_CELL_VALUES_IN_FIELDS' as const,
    UNSUBSCRIBE_FROM_CELL_VALUES_IN_FIELDS: 'UNSUBSCRIBE_FROM_CELL_VALUES_IN_FIELDS' as const,
    FETCH_AND_SUBSCRIBE_TO_CURSOR_DATA: 'FETCH_AND_SUBSCRIBE_TO_CURSOR_DATA' as const,
    UNSUBSCRIBE_FROM_CURSOR_DATA: 'UNSUBSCRIBE_FROM_CURSOR_DATA' as const,
    EXPAND_RECORD: 'EXPAND_RECORD' as const,
    EXPAND_RECORD_LIST: 'EXPAND_RECORD_LIST' as const,
    EXPAND_RECORD_PICKER: 'EXPAND_RECORD_PICKER' as const,
    SET_MULTIPLE_KV_PATHS: 'SET_MULTIPLE_KV_PATHS' as const,
    SET_CELL_VALUES: 'SET_CELL_VALUES' as const,
    CREATE_RECORDS: 'CREATE_RECORDS' as const,
    DELETE_RECORDS: 'DELETE_RECORDS' as const,
    ENTER_FULLSCREEN: 'ENTER_FULLSCREEN' as const,
    EXIT_FULLSCREEN: 'EXIT_FULLSCREEN' as const,
    SET_FULLSCREEN_MAX_SIZE: 'SET_FULLSCREEN_MAX_SIZE' as const,
    SET_SETTINGS_BUTTON_VISIBILITY: 'SET_SETTINGS_BUTTON_VISIBILITY' as const,
    SET_UNDO_REDO_MODE: 'SET_UNDO_REDO_MODE' as const,
});

export type BlockToHostMessageType = ObjectValues<typeof BlockToHost>;
export type HostToBlockMessageType = ObjectValues<typeof HostToBlock>;
export type HostMethodName = ObjectValues<typeof HostMethodNames>;
