# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: SDK Docs

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-18.04
        timeout-minutes: 30
        steps:
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '8.x'

            - uses: actions/checkout@v1

            - name: Setup git
              run: |
                  git config --local user.email "airtable@users.noreply.github.com"
                  git config --local user.name "Airtable"
                  git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
                  git checkout ${GITHUB_REF##refs/heads/}

            - name: Install dependencies
              run: |
                  # HACK: we can't install eslint-plugin-airtable because it's a private git
                  # dependency. We don't actually need it for generating the docs though, so we can
                  # just sneakily remove it for now.
                  sed -i '/"eslint-plugin-airtable":/d' ./packages/cli/package.json
                  sed -i '/"eslint-plugin-airtable":/d' ./packages/sdk/package.json
                  yarn --non-interactive

                  # after we've installed everything, we should reset package.json and yarn.lock
                  # back to how they were before - they get changed after the `sed` hack above:
                  git add -A
                  git reset --hard HEAD

            - name: Build & format docs
              run: |
                  cd packages/sdk
                  yarn run build:types
                  yarn run docs
                  git add docs/api
                  cd ../..
                  yarn run pretty-quick --staged

            - name: Commit & push changes
              # if no changes are made, the commit will be empty and this step will fail. That's
              # valid though! Also, `git push` might fail because new commits have been pushed in
              # the mean time - that's fine too!
              continue-on-error: true
              run: |
                  git commit --no-verify -m "sdk: generate docs for $(git rev-parse --short HEAD) [automated]" -m "This commit was generated by .github/workflows/sdk-docs.yml on $(date)."
                  git push
